FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /mdm-server ./cmd/server

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /mdm-server /mdm-server
COPY --from=builder /app/db /db
WORKDIR /
EXPOSE 8080
ENTRYPOINT ["/mdm-server"]
